### ISSUE TITLE
[CSS Frameworks] Installation Bootstrap

### ISSUE THREAD

**Issue by holabee** [holabee/CSS-frameworks#1]
To set up latest bootstrap 

```bash

npm i bootstrap@next

```

Bundler
- parcel

**Comment by Ankita-singh-05** [comment]
I want to work on this particular issue can you please assign it to me?

**Comment by holabee** [comment]
@Ankita-singh-05  Well... I just considered a  daily newspaper website to build. Do you mind if i assign to you?

**Comment by holabee** [comment]
> I want to work on this particular issue can you please assign it to me?
